/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisplaySlugRouteImport } from './routes/display/$slug'
import { Route as AdminTestIndexRouteImport } from './routes/admin/test/index'
import { Route as AdminOfficesIndexRouteImport } from './routes/admin/offices/index'
import { Route as AdminCarsIndexRouteImport } from './routes/admin/cars/index'
import { Route as AdminCarGroupsIndexRouteImport } from './routes/admin/car-groups/index'
import { Route as AdminBrandsIndexRouteImport } from './routes/admin/brands/index'

const DisplaySlugRoute = DisplaySlugRouteImport.update({
  id: '/display/$slug',
  path: '/display/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestIndexRoute = AdminTestIndexRouteImport.update({
  id: '/admin/test/',
  path: '/admin/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOfficesIndexRoute = AdminOfficesIndexRouteImport.update({
  id: '/admin/offices/',
  path: '/admin/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarsIndexRoute = AdminCarsIndexRouteImport.update({
  id: '/admin/cars/',
  path: '/admin/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarGroupsIndexRoute = AdminCarGroupsIndexRouteImport.update({
  id: '/admin/car-groups/',
  path: '/admin/car-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsIndexRoute = AdminBrandsIndexRouteImport.update({
  id: '/admin/brands/',
  path: '/admin/brands/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands/': typeof AdminBrandsIndexRoute
  '/admin/car-groups/': typeof AdminCarGroupsIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/offices/': typeof AdminOfficesIndexRoute
  '/admin/test/': typeof AdminTestIndexRoute
}
export interface FileRoutesByTo {
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands': typeof AdminBrandsIndexRoute
  '/admin/car-groups': typeof AdminCarGroupsIndexRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/offices': typeof AdminOfficesIndexRoute
  '/admin/test': typeof AdminTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands/': typeof AdminBrandsIndexRoute
  '/admin/car-groups/': typeof AdminCarGroupsIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/offices/': typeof AdminOfficesIndexRoute
  '/admin/test/': typeof AdminTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/display/$slug'
    | '/admin/brands/'
    | '/admin/car-groups/'
    | '/admin/cars/'
    | '/admin/offices/'
    | '/admin/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/display/$slug'
    | '/admin/brands'
    | '/admin/car-groups'
    | '/admin/cars'
    | '/admin/offices'
    | '/admin/test'
  id:
    | '__root__'
    | '/display/$slug'
    | '/admin/brands/'
    | '/admin/car-groups/'
    | '/admin/cars/'
    | '/admin/offices/'
    | '/admin/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DisplaySlugRoute: typeof DisplaySlugRoute
  AdminBrandsIndexRoute: typeof AdminBrandsIndexRoute
  AdminCarGroupsIndexRoute: typeof AdminCarGroupsIndexRoute
  AdminCarsIndexRoute: typeof AdminCarsIndexRoute
  AdminOfficesIndexRoute: typeof AdminOfficesIndexRoute
  AdminTestIndexRoute: typeof AdminTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/display/$slug': {
      id: '/display/$slug'
      path: '/display/$slug'
      fullPath: '/display/$slug'
      preLoaderRoute: typeof DisplaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/test/': {
      id: '/admin/test/'
      path: '/admin/test'
      fullPath: '/admin/test/'
      preLoaderRoute: typeof AdminTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/offices/': {
      id: '/admin/offices/'
      path: '/admin/offices'
      fullPath: '/admin/offices/'
      preLoaderRoute: typeof AdminOfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/admin/cars'
      fullPath: '/admin/cars/'
      preLoaderRoute: typeof AdminCarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/car-groups/': {
      id: '/admin/car-groups/'
      path: '/admin/car-groups'
      fullPath: '/admin/car-groups/'
      preLoaderRoute: typeof AdminCarGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands/': {
      id: '/admin/brands/'
      path: '/admin/brands'
      fullPath: '/admin/brands/'
      preLoaderRoute: typeof AdminBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DisplaySlugRoute: DisplaySlugRoute,
  AdminBrandsIndexRoute: AdminBrandsIndexRoute,
  AdminCarGroupsIndexRoute: AdminCarGroupsIndexRoute,
  AdminCarsIndexRoute: AdminCarsIndexRoute,
  AdminOfficesIndexRoute: AdminOfficesIndexRoute,
  AdminTestIndexRoute: AdminTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
