/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisplaySlugRouteImport } from './routes/display/$slug'
import { Route as AdminBrandsIndexRouteImport } from './routes/admin/brands/index'

const DisplaySlugRoute = DisplaySlugRouteImport.update({
  id: '/display/$slug',
  path: '/display/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandsIndexRoute = AdminBrandsIndexRouteImport.update({
  id: '/admin/brands/',
  path: '/admin/brands/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands/': typeof AdminBrandsIndexRoute
}
export interface FileRoutesByTo {
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands': typeof AdminBrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/display/$slug': typeof DisplaySlugRoute
  '/admin/brands/': typeof AdminBrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/display/$slug' | '/admin/brands/'
  fileRoutesByTo: FileRoutesByTo
  to: '/display/$slug' | '/admin/brands'
  id: '__root__' | '/display/$slug' | '/admin/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DisplaySlugRoute: typeof DisplaySlugRoute
  AdminBrandsIndexRoute: typeof AdminBrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/display/$slug': {
      id: '/display/$slug'
      path: '/display/$slug'
      fullPath: '/display/$slug'
      preLoaderRoute: typeof DisplaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brands/': {
      id: '/admin/brands/'
      path: '/admin/brands'
      fullPath: '/admin/brands/'
      preLoaderRoute: typeof AdminBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DisplaySlugRoute: DisplaySlugRoute,
  AdminBrandsIndexRoute: AdminBrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
